name = "cesar-zero-service-runner"
main = "src/services/index.ts"
compatibility_date = "2024-04-03"
account_id = "085f6d8eb08e5b23debfb08b21bda1eb"
node_compat = true
logpush = true
durable_objects.bindings = [{ name = "runnerDO", class_name = "RunnerDO" }]


[vars]
LOG_LEVEL = "info"
UPSTREAM_URI = "postgresql://postgres:Dy0sWZ23jehvUjCG@db.abxajxywikberyafnvdf.supabase.co:5432/postgres"
SYNC_REPLICA_URI = "postgres://postgres:PflboBSekWHTkhJ2@ec2-18-157-106-72.eu-central-1.compute.amazonaws.com:5432/postgres"


[[migrations]]
tag = "v1"
new_classes = ["runnerDO"]

[build]
# command = "npm run build-worker"
# don't watch all resources because we want to run without --persist when
# possible, so restarts delete data.
watch_dir = "src/services"

#[triggers]
#crons = [ "*/5 * * * *" ] # ever 5 mins for AuthDO connection revalidation
